version: '3.2'

services:
  client:
    build:
      context: .
      dockerfile: Client.Dockerfile
    volumes:
      - ./dist:/app/dist # mapping docker generated file with local

  
  web:
    build: .
    volumes:
      - ./dist:/app/dist # Mapping docker generated file with local
      - ./backend:/app/backend # Mapping docker generated file with local
    entrypoint: /app/entrypoint.sh
    ports:
      - 8001:8001
    depends_on:
      - client
